home:
    path: /
    defaults:
        _controller: 'Slim\Controllers\IndexController::indexAction'
login:
    path: /login
    defaults:
        _controller: 'Slim\Controllers\IndexController::loginAction'
login_check:
    path: /login_check
    defaults:
        _controller: 'IndexController::loginCheckAction'

admin:
    path: /admin
    defaults:
        _controller: 'Slim\Controllers\Admin\AdminController::indexAction'



api:
    prefix: api/
    resource: "routes/api.yml"
