
services:

    memcached:
        class: Memcached
        calls:
            -
                - addServer
                -
                    - '%app.memcached.host%'
                    - '%app.memcached.port%'
    entity_manager:
        class: Doctrine\ORM\EntityManager
        factory:
            - Slim\Database\Database
            - getEntityManager

    memcache:
        class: Doctrine\Common\Cache\MemcachedCache
        factory:
            - Slim\Database\Database
            - getMemcache
    user_provider:
        class: Slim\Providers\UserProvider
