is_debug: true
dir:
    log: /data/logs/slimphp
    data: /data/slimphp
    cache: /Users/luguo/Documents/wwwroot/slim-php/cache
    template: /Users/luguo/Documents/wwwroot/slim-php/template
db:
    host: 127.0.0.1
    port: 3306
    user: root
    password: 123456
    dbname: slim
memcached:
    host: 127.0.0.1
    port: 11211
